import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico, Lora, Noto_Serif_KR } from "next/font/google";
import { AuthProvider } from "@/components/AuthProvider";
import "./globals.css";

const lora = Lora({
  weight: ['400', '500', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lora',
});

const notoSerifKr = Noto_Serif_KR({
  weight: ['400', '500', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-serif-kr',
});

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} ${lora.variable} ${notoSerifKr.variable} antialiased`}
      >
        <AuthProvider>
          <div
            className="min-h-screen bg-[#f8f6f2]"
            style={{
              backgroundImage:
                'radial-gradient(circle at 20% 10%, rgba(251, 191, 36, 0.14), transparent 50%), radial-gradient(circle at 80% 0%, rgba(245, 158, 11, 0.12), transparent 45%)',
              backgroundAttachment: 'fixed',
            }}
          >
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
